CREATE TABLE Shops(
    ShopName VARCHAR(100) PRIMARY KEY
);
CREATE TABLE Products(
    ProductName VARCHAR(300) PRIMARY KEY,
    Maker VARCHAR(500) NOT NULL,
    Category VARCHAR(200) NOT NULL,
);
CREATE TABLE Users(
    UserId INT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL
);
CREATE TABLE Employee(
    EmpId INT PRIMARY KEY,
    EmpName VARCHAR (50) NOT NULL,
    Salary MONEY NOT NULL
);
CREATE TABLE Orders(
    OrderId INT PRIMARY KEY,
    UserId INT NOT NULL REFERENCES Users(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    ShippingAddress VARCHAR(1000) NOT NULL,
    Order_DateTime DATETIME NOT NULL
);
CREATE TABLE ProductsInOrder(
    ShopName VARCHAR(100) NOT NULL REFERENCES Shops(ShopName) ON DELETE CASCADE ON UPDATE CASCADE,
    ProductName VARCHAR(300) NOT NULL REFERENCES Products(ProductName) ON DELETE CASCADE ON UPDATE CASCADE,
    OrderId INT NOT NULL REFERENCES Orders(OrderId) ON DELETE CASCADE ON UPDATE CASCADE,
    DeliveredDate DATETIME NOT NULL,
    OrderStatus VARCHAR(100) NOT NULL,
    Price MONEY NOT NULL,
    Quantity INT NOT NULL
    PRIMARY KEY(ProductName, OrderId)
);

CREATE TABLE ProductInShops(
    ShopName VARCHAR(100) NOT NULL REFERENCES Shops(ShopName) ON DELETE CASCADE ON UPDATE CASCADE,
    ProductName VARCHAR(300) NOT NULL REFERENCES Products(ProductName) ON DELETE CASCADE ON UPDATE CASCADE,
    Price MONEY NOT NULL,
    Quantity INT NOT NULL,
    PRIMARY KEY(ShopName,ProductName)
);
CREATE TABLE PriceHistory(
    ShopName VARCHAR(100) NOT NULL REFERENCES Shops(ShopName) ON DELETE CASCADE ON UPDATE CASCADE,
    ProductName VARCHAR(300) NOT NULL REFERENCES Products(ProductName) ON DELETE CASCADE ON UPDATE CASCADE,
    Price MONEY NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL
);
CREATE TABLE Complaints(
    ComplaintId INT PRIMARY KEY,
    EmpId INT NOT NULL REFERENCES Employee(EmpId) ON DELETE CASCADE ON UPDATE CASCADE,
    UserId INT NOT NULL REFERENCES Users(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    Filed_DateTime DATETIME NOT NULL,
    Handled_DateTime DATETIME,
    ComplaintStatus VARCHAR(50) NOT NULL,
    ComplaintText VARCHAR(2000) NOT NULL
);
CREATE TABLE OrderComplaints(
    ComplaintId INT NOT NULL REFERENCES Complaints(ComplaintId) ON DELETE NO ACTION ON UPDATE NO ACTION,
    OrderId INT NOT NULL REFERENCES Orders(OrderId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ComplaintId)
);
CREATE TABLE ShopComplaints(
    ComplaintId INT NOT NULL REFERENCES Complaints(ComplaintId) ON DELETE NO ACTION ON UPDATE NO ACTION ,
    ShopName VARCHAR(100) NOT NULL REFERENCES Shops(ShopName) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ComplaintId)
);
CREATE TABLE Feedback(
    ProductName VARCHAR(300) NOT NULL REFERENCES Products(ProductName) ON DELETE CASCADE ON UPDATE CASCADE,
    UserId INT NOT NULL REFERENCES Users(UserId) ON DELETE CASCADE ON UPDATE CASCADE,
    Rating INT NOT NULL,
    Comment VARCHAR(1000) NOT NULL,
    FeedbackDate DATETIME NOT NULL,
    PRIMARY KEY(ProductName,UserId)
);
